[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--include=optional"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[context.deploy-preview.headers]]
  for = "/*"
  [context.deploy-preview.headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[context.branch-deploy.headers]]
  for = "/*"
  [context.branch-deploy.headers.values]
    X-Robots-Tag = "noindex, nofollow"

[context.deploy-preview.environment]
  GATSBY_RECAPTCHA_KEY = "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"

[context.branch-deploy.environment]
  GATSBY_RECAPTCHA_KEY = "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
